version: "3"

services:
  project-api_fred-test-db:
    image: postgres:11.12
    container_name: project-api_fred-test-db
    volumes:
      - ./project-api_fred-test-db:/var/lib/postgresql/data
      - ./src/main/resources/docker/postgresql/init_schema.sql:/docker-entrypoint-initdb.d/init_schema.sql
      - ./src/main/resources/docker/postgresql/init_schema_public.sql:/docker-entrypoint-initdb.d/init_schema_public.sql
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
  
  project-api_fred-local-db:
    image: postgres:11.12
    container_name: project-api_fred-local-db
    volumes:
      - project-api_fred-local-db:/var/lib/postgresql/data
      - ./src/main/resources/docker/postgresql/init_schema_public.sql:/docker-entrypoint-initdb.d/init_schema_public.sql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

volumes:
  project-api_fred-test-db:
    driver: local
  project-api_fred-local-db:
    driver: local